version: '3'
services:
  redis:
    image: redis
    container_name: redis-server
    networks:
      - net
    ports:
      - "6379:6379"
  api:
    container_name: flask-api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net
    ports:
      - '5000:5000'
    depends_on:
      - redis  
  tg_bot:
    container_name: tg_bot
    build:
      context: .
      dockerfile: Dockerfile_bot
    env_file:
      - env.txt
    depends_on:
      - redis
      - api
    networks:
      - net
networks:
  net:
    driver: bridge