version: '3'
services:
  api:
    container_name: flask-container
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"